# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - docker build . -t portable-faster-whisper
  bash:
    cmds:
      - docker run --gpus all -v ${PWD}:/workspace -it portable-faster-whisper /bin/bash
    silent: true
